[package]
name = "gen_graph"
version = "0.1.0"
authors = ["Rannveig Varisedottir <ElementalRannveig@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.17.0"
structopt = "0.3.23"
chrono = "0.2.16"
